export const LOGIN = 'LOGIN';
export const LOGINPROGRESS = 'LOGINPROGRESS';
export const GETHOMEDATA = 'GETHOMEDATA';
export const GETDASHBOARDDATA = 'GETDASHBOARDDATA';
export const TOKENEXPIRED = 'TOKENEXPIRED';
export const RESIGNIN = 'RESIGNIN';
